### PR TITLE
Fix DuplicateWidgetID error

### PR DESCRIPTION
**Pull request by MatiasVasquezOrrego**
Hey, I saw your guide on YouTube and I encountered an error that I noticed more people had experienced. I found a solution that creates a key for each historical chat text.

### CODE REVIEW

**Comment by andfanilo** [comment]
Thanks for the PR :) it is really helpful!

Instead of creating a range of indices and then asking for the i-nth element of the chat history, you can use `enumerate` like: 

`for i, chat in enumerate(st.session_state.history):`

and then use `i` for the key and `chat` for the message. It's not much in performance terms but it's generally more usable.

Could you edit your PR?

Have a nice day,
Fanilo

**Comment by MatiasVasquezOrrego** [comment]
Yeah sure, thanks for bringing that up i will edit it and create a new pr with the changes

**Comment by andfanilo** [comment]
Actually this PR will track any commits you do on the branch, so you can also just push a new commit on this branch with the edits :) give it a try!

**Comment by MatiasVasquezOrrego** [comment]
thanks for that, i will give it a try

**Comment by andfanilo** [comment]
Thanks! Great job if that's your first contribution, this was very helpful :) thanks for taking the time to do it
Have a nice day!
Fanilo

**Pull request merged**
